title: Justin McKinney - GitHub Pages
description: This site will be used to house my CS Capstone artifacts.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
