title: Justin McKinney - GitHub Pages
description: This site will be used to house my CS Capstone artifacts. Artifact one: <a href="https://github.com/JMckinney13/JMckinney13.github.io/blob/main/ArtifactOne.py"> Something </a>
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
<a href="https://github.com/JMckinney13/JMckinney13.github.io/blob/main/ArtifactOne.py"> Something </a>
